### ISSUE TITLE
issues i've found

### ISSUE THREAD

**Issue by 02ismywaifu** [FukutoTojido/beatmap-viewer-web#39]
1. sound going bonkers when u put on ht/dt. map(s) used to test: 
_**4047519**_
_**3977191**_     (whistle noise appearing when dt)

2. song not loading. map(s) used to test: 
_**2536330**_     (error: TypeError: Cannot read properties of undefined (reading 'x'))
_**1529760**_     (error: RangeError: Invalid array length)
_**2087153**_     (error: TypeError: Cannot read properties of undefined (reading 'x'))

3. 2b. map(s) used to test: 
_**272317**_     (at roughly 11 seconds u can see a big slider, then it disappears without completing it, also if u pause u will hear slider ball noise(happens to most of the sliders on the map)).
    at roughly 26 and 32 seconds u can see objects just randomly popping on ur screen and the objects on the timeline(or whatever the thing at the top with objects is called) disappear. u can see that throughout the whole map also.)
_**1013379**_     (same problems as above, first issue occurs roughly at 20 seconds, second issue occurs roughly at 32 seconds)

**Comment by FukutoTojido** [comment]
> sound going bonkers when u put on ht/dt. map(s) used to test:
> - 4047519
> - 3977191 (whistle noise appearing when dt)

It is an expected behaviour due to the nature of the current time stretch library. I can do nothing about that.

> song not loading. map(s) used to test:
> - 2536330 (error: TypeError: Cannot read properties of undefined (reading 'x'))
> - 1529760 (error: RangeError: Invalid array length)
> - 2087153 (error: TypeError: Cannot read properties of undefined (reading 'x'))

Aspire maps are ... pretty much problematic. However, I manage to get `2536330` and `1529760` work (barely tho). Except for `2087153`, I think I have to disable it from being loaded on the site because of how cursed it is which lead to the site freezing if I manage to get it run.

> 2B map(s) used to test:
> - 272317 (at roughly 11 seconds u can see a big slider, then it disappears without completing it, also if u pause u will hear slider ball noise(happens to most of the sliders on the map)).
at roughly 26 and 32 seconds u can see objects just randomly popping on ur screen and the objects on the timeline(or whatever the thing at the top with objects is called) disappear. u can see that throughout the whole map also.)
> - 1013379 (same problems as above, first issue occurs roughly at 20 seconds, second issue occurs roughly at 32 seconds)

The problem is coming from the overlapping nature of 2B maps. My algorithm is based on the principle that each object time window will not overlap with each other and I'll manually insert / remove object to the playfield according to the timing of the first and the last object. Therefore, some objects in 2B maps will be removed out of the playfield sooner than they expected to be simply because the timing of the 2B slider has gone out of the time window between the first and the last object. Maybe I'll work on this in the future but for now, I'll just let it be.
